// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqm-voL9LhzZCYbdfh_zML60i79koRA24',
    appId: '1:467331489176:web:dfc89bf1d3681cb3821fed',
    messagingSenderId: '467331489176',
    projectId: 'expense-tracker-app-e4d4c',
    authDomain: 'expense-tracker-app-e4d4c.firebaseapp.com',
    storageBucket: 'expense-tracker-app-e4d4c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC66EmsxeH07XWt1MERhnmw2z-eRpGPmvk',
    appId: '1:467331489176:android:81430f28a3cb4a70821fed',
    messagingSenderId: '467331489176',
    projectId: 'expense-tracker-app-e4d4c',
    storageBucket: 'expense-tracker-app-e4d4c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAq5tlFKmlIKcLzZesJJlC9DTXTc4RJXc',
    appId: '1:467331489176:ios:f315cb929e846f66821fed',
    messagingSenderId: '467331489176',
    projectId: 'expense-tracker-app-e4d4c',
    storageBucket: 'expense-tracker-app-e4d4c.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAq5tlFKmlIKcLzZesJJlC9DTXTc4RJXc',
    appId: '1:467331489176:ios:f315cb929e846f66821fed',
    messagingSenderId: '467331489176',
    projectId: 'expense-tracker-app-e4d4c',
    storageBucket: 'expense-tracker-app-e4d4c.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqm-voL9LhzZCYbdfh_zML60i79koRA24',
    appId: '1:467331489176:web:0a88e34715c136c9821fed',
    messagingSenderId: '467331489176',
    projectId: 'expense-tracker-app-e4d4c',
    authDomain: 'expense-tracker-app-e4d4c.firebaseapp.com',
    storageBucket: 'expense-tracker-app-e4d4c.firebasestorage.app',
  );
}
