// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXQ4YIYr_He8Gl4yXCKL4RokN6cH-Rqo4',
    appId: '1:601322984160:web:40584aaa2a63462fcef685',
    messagingSenderId: '601322984160',
    projectId: 'taskmanagerapp-7d39d',
    authDomain: 'taskmanagerapp-7d39d.firebaseapp.com',
    storageBucket: 'taskmanagerapp-7d39d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADffkldDDLGF0bFna9O-EHun76KIamHEs',
    appId: '1:601322984160:android:7a76238505447d31cef685',
    messagingSenderId: '601322984160',
    projectId: 'taskmanagerapp-7d39d',
    storageBucket: 'taskmanagerapp-7d39d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChZEix_BsutRVK-KLZ9xXQ_zpARwvb7g0',
    appId: '1:601322984160:ios:a1ace3ce0a898ebacef685',
    messagingSenderId: '601322984160',
    projectId: 'taskmanagerapp-7d39d',
    storageBucket: 'taskmanagerapp-7d39d.firebasestorage.app',
    iosBundleId: 'com.example.taskManagerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChZEix_BsutRVK-KLZ9xXQ_zpARwvb7g0',
    appId: '1:601322984160:ios:a1ace3ce0a898ebacef685',
    messagingSenderId: '601322984160',
    projectId: 'taskmanagerapp-7d39d',
    storageBucket: 'taskmanagerapp-7d39d.firebasestorage.app',
    iosBundleId: 'com.example.taskManagerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXQ4YIYr_He8Gl4yXCKL4RokN6cH-Rqo4',
    appId: '1:601322984160:web:785d35be07aeaaf4cef685',
    messagingSenderId: '601322984160',
    projectId: 'taskmanagerapp-7d39d',
    authDomain: 'taskmanagerapp-7d39d.firebaseapp.com',
    storageBucket: 'taskmanagerapp-7d39d.firebasestorage.app',
  );

}