// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrCoaI-HAyVH1xM0SVLUtNm1K8Vo003_4',
    appId: '1:1039386150858:web:33fc79b96bf1c97bdaf133',
    messagingSenderId: '1039386150858',
    projectId: 'shadi-ecommerce',
    authDomain: 'shadi-ecommerce.firebaseapp.com',
    storageBucket: 'shadi-ecommerce.appspot.com', // ✅ fixed
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFEK4vAQNbcQ_Vnmvy-2ajOiBoNgeNAWY',
    appId: '1:1039386150858:android:26eef02567a8b259daf133',
    messagingSenderId: '1039386150858',
    projectId: 'shadi-ecommerce',
    storageBucket: 'shadi-ecommerce.appspot.com', // ✅ fixed
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKBQKJYOWAuEw5hNIuD3Lvdbi6dD83SM4',
    appId: '1:1039386150858:ios:084b636115984853daf133',
    messagingSenderId: '1039386150858',
    projectId: 'shadi-ecommerce',
    storageBucket: 'shadi-ecommerce.appspot.com', // ✅ fixed
    iosBundleId: 'com.example.ecommerceUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKBQKJYOWAuEw5hNIuD3Lvdbi6dD83SM4',
    appId: '1:1039386150858:ios:084b636115984853daf133',
    messagingSenderId: '1039386150858',
    projectId: 'shadi-ecommerce',
    storageBucket: 'shadi-ecommerce.appspot.com', // ✅ fixed
    iosBundleId: 'com.example.ecommerceUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrCoaI-HAyVH1xM0SVLUtNm1K8Vo003_4',
    appId: '1:1039386150858:web:6b93ed1a9753c8dadaf133',
    messagingSenderId: '1039386150858',
    projectId: 'shadi-ecommerce',
    authDomain: 'shadi-ecommerce.firebaseapp.com',
    storageBucket: 'shadi-ecommerce.appspot.com', // ✅ fixed
  );
}
